import Head from 'next/head'
import { useEffect, useState, useCallback } from 'react';
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic';
import MainWeather from '../components/mainweather'
const VMap = dynamic(
  () => import('../components/vmaps'), // replace '@components/map' with your component's location
  { ssr: false } // This line is important. It's what prevents server-side render
)

export default function Home() {

  const [latlong, setLatLong] = useState([51.505,-0.09])
  const [error, setError] = useState(false)

    useEffect(() => {
       navigator.geolocation.getCurrentPosition((loc) => {
        setLatLong([loc.coords.latitude,loc.coords.longitude])
      }, (err) => {
        setError(err.code)
      })
    }, [])

    
    const callback = useCallback((coords) => {
      setLatLong(coords);
    }, []);


  return (
    <div className={styles.container}>
      <Head>
        <title>Weather</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <h2 className={styles.title}>
          Best Guess Location
          or center on location
        </h2>  
      
      
      <VMap latlong={latlong} parentCallback={callback} />
      <MainWeather slatlong={latlong} />  
      </main>
      
      <footer className={styles.footer}>
            Data Provided by <div><a href="https://open-meteo.com/">https://open-meteo.com/</a></div>
      </footer>
    </div>
  ) 
}
